services:
  - type: web
    name: jamie-backend
    env: node
    plan: standard
    numInstances: 1  # Minimum instances (autoscaling will increase as needed)
    buildCommand: cd jamie-backend && npm install
    startCommand: cd jamie-backend && npm start
    rootDir: jamie-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

